### ISSUE TITLE
v1.1 still under development? 

### ISSUE THREAD

**Issue by halmos** [mtcaptcha-public/MTCaptcha-wordpress-plugin#3]
Hi, thank you for developing this service / plugin. We are eager to use MTCaptcha but require support for Contact Form 7. Is there any updates for a 1.1 release? 

thank you.

**Comment by batou-mtcapthca** [comment]
Please use the latest version from this repository, it has the Contact From 7 Support

**Comment by matrixs911atlas33-collab** [comment]
Turkiye mersındeyım sarı uyarı YellowNotıce 5 yıldır sıber saldırı honey trap deep fake kabloları ile bal tuzağı işkence eziyet kasten cinayet göcmen tıcaretı ırkçılık soykırım yabancı dusmanlıgı avustralya baglantılı Nardane Cerit sülalesı 0538 722 90 14 tarafından kacırıldım sadist Tarık İdemci pınar idemci tarafından işkence Tarık İdemci 0533 501 81 13 burası siyahi FBI CIA911 amerıkan istihbarat fedaral abim oşdugıkdan soybagı degıstırme matrixs911.atlas33@gmail.com 05461599795 20689001488 acil durum Turkiye cumhuriyet TCK kanunları anayasanın oldugu ülkede mersın adana şehrinde sokak ortasında hergun hrıstıyanö dıye ırkcı emmiyet guclwrı tarafndan da iş birliği yapılarak sessiz ulusarası cıglık attığım halde gornezden gelerek cerıt sulalesının dıger kadın ve cocukları sokak ortasında normal bşrsekilde işkence ile öldurup kölelik sistemi yapıp hergun eziyet zulm edilen mersın ilinde Yunanistan dan kaçırılan çocuklar da dahil sokak ortasında zorla calıstırılıp soybagı degıstırme tecavüz fuhusa zorlama intihara sürükleme bal tuzağı sanal ortamda uluslararası cıglık da atsalar duyulmuyor ve katlediliyor gecen yıl bır kadının tv cıkıp da film oldugu sehir burası mersın tum kadınlar cocuklar burada işkence ve eziyet ölduruluyıt burası turkiye cumhuriyet TCK kanunları anayasanın oldugu ülkede emniyet guclwrı tarafından da katledip Tarık İdemci ile anlaşma yapılıyor sırf hrıstıyan yada ermeni yada yahudi dıye cok fazla cinayet suan eblerde zorla alkonularak işkence goren yabancı uyruklu kişiler var burada yabancı dusmanlıgı 20689001488 05461599795 ABD buyuk elçilikden bilgi ve savas acılmış durumu bu ben amerıkan vat ve zorla tutuluyorum annemide bu serı katil öldurdugu mu bilen polıslerın okadar sıkayet ciddiye anlayarak 14 yıldır bu işi emniyet guclwrı ile profesyonel yapan deas iid chatclar elşndryim

**Comment by matrixs911atlas33-collab** [comment]
Turkiye mersındeyım ihbar palpito 0533 501 81 13 suikastcı can guvenligim riskim vardır Tarık İdemci Nardane cerıt kadir cerıt avustralya dan gelen katil soybagı degıstırme honey sadist ınterpol uluslararası cınayet masa ya bilgi savaş
